connections:
    con_oltp:
        ormmetadata: true
        default: true
        dbname: 'webapidb'
        user: 'webapiuser'
        password: 'webapipass'
        host: '127.0.0.1'
        driver: 'pdo_mysql'
    con_logger:
        ormmetadata: false
        dbname: 'webapi_logger'
        driver: 'sqlite'
cli_connection: 'con_oltp'